

const foods=[
    {
        id:'1',
        name:'Pizza de Carne',
        ingredientes:'Carne Pizza',
        precio: '7.50',
        image: require('../assets/carnePizza.png'),
        detalles: "Creada para el amante de carne que existe dentro tuyo. La pizza de carne contiene tus ingredientes favoritos en abundancia: pepperoni, salchicha, carne de res, tocino ahumado, jamón y queso mozzarella. Una explosión de sabores.",
    },
    {
        id:'2',
        name:'Pizza de Queso',
        ingredientes:'Queso Pizza',
        precio: '8.50',
        image: require('../assets/quesoPizza.png'),
        detalles: '¡Experimenta el sabor auténtico de Italia! Nuestra deliciosa pizza de queso está cubierta con salsa de pizza y seis quesos premium: mozzarella, parmesano, romano, asiago, provolone y fontina. Caliente y fresca.',
    },
    {
        id:'3',
        name:'Pizza Suprema',
        ingredientes:'Suprema Pizza',
        precio: '9.50',
        image: require('../assets/suprema-pizza.png'),
        detalles: 'Salchica Italiana, chile verde, cebolla jamón y pepperoni..',
    },
    {
        id:'4',
        name:'Pizza de Peperoni',
        ingredientes:'Peperoni Pizza',
        precio: '6.50',
        image: require('../assets/peperoni-pizza.png'),
        detalles: 'La pizza simple, pero igual que todo genial, los dos componentes y la increíble plenitud de sabor. con salsa de tomate, pepperoni y queso mozzarella.',
    },
         //PASTAS
    {
        id:'5',
        name:'Pasta Carne',
        ingredientes:'Carne Pasta',
        precio: '5.50',
        image: require('../assets/pasta-carne.png'),
        detalles: 'Combinación de salsa de ajo, hongos, cebolla, carne de res, tocino, salsa de pizza, salsa Ranch. Mezcla de quesos romano y Parmesano, con toque picante.',
    },
    {
        id:'6',
        name:'Pasta Queso',
        ingredientes:'Queso Pastas',
        precio: '6.00',
        image: require('../assets/pasta-queso.png'),
        detalles: '!Irresistible sabor! Salsa de ajo Parmesano, tomate, hongos, jamón y mezcla de quesos Romano, Mozzarella y Parmesano, con un toque de oregano.',
    },
    {
        id:'7',
        name:'Pasta Salsa',
        ingredientes:'Salsa Pastas',
        precio: '6.00',
        image: require('../assets/pasta-salsa.png'),
        detalles: 'Pasta bañada con salsa de tomate preparada por nosotros',
    },
    {
        id:'8',
        name:'Pasta Vegetariana',
        ingredientes:'Vegetal Pastas',
        precio: '4.00',
        image: require('../assets/pasta-vegetal.png'),
        detalles: 'Nuestra especialidad de la casa, hecha con parmesano reggiano, vino blanco flameado, pimienta negra y crema de leche.',
    },
///bebidas
{
    id:'9',
    name:'Coca Cola',
    ingredientes:'Coca Cola',
    precio: '1.00',
    image: require('../assets/cocacola.png'),
    detalles: 'Bebida sabor coca cola de 335ml.',
},
{
    id:'10',
    name:'Fanta',
    ingredientes:'fanta',
    precio: '1.00',
    image: require('../assets/fanta.png'),
    detalles: 'Bebida sabor naranja de 335ml.',
},
{
    id:'11',
    name:'Fanta uva',
    ingredientes:'uva',
    precio: '1.00',
    image: require('../assets/uva.png'),
    detalles: 'Bebida sabor uva de 335ml.',
},
{
    id:'12',
    name:'Sprite',
    ingredientes:'Sprite',
    precio: '1.00',
    image: require('../assets/sprite.png'),
    detalles: 'Bebida sabor sprite de 335ml.',
},
{
    id:'13',
    name:'Pepsi',
    ingredientes:'Pepsi',
    precio: '1.00',
    image: require('../assets/pepsi.png'),
    detalles: 'Bebida sabor pepsi de 335ml.',
},
{
    id:'13',
    name:'agua',
    ingredientes:'agua',
    precio: '1.00',
    image: require('../assets/agua.png'),
    detalles: 'Agua de 335ml.',
},
];
export default foods;